services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:10
    container_name: forgejo
    restart: always
    environment:
      - FORGEJO__METRICS__ENABLED=true
      - FORGEJO__LOGS__MODE=database
      - FORGEJO__LOGS__DATABASE=postgres://postgres:password@db:5432/forgejo_logs
    ports:
      - "3000:3000"
    volumes:
      - forgejo-data:/data
    depends_on:
      - db
    networks:
      - monitoring

  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: forgejo_logs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    depends_on:
      - sidecar_exporter
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - db
      - prometheus
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: always
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    ports:
      - "9093:9093"
    networks:
      - monitoring

  sidecar_exporter:
    build: ./exporter
    container_name: sidecar_exporter
    restart: always
    ports:
      - "8000:8000"
    networks:
      - monitoring

volumes:
  forgejo-data:
  db-data:
  grafana-data:

networks:
  monitoring:
    driver: bridge
